baseURL = "/"
languageCode = "en-us"
title = "Frech Takes"
theme = "ezhil"
paginate = 5

copyright = "© 2022 Scott Frechette"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
#disqusShortname = "frechtakes"

summaryLength = 10

[params]
	subtitle = "Cooking up a new batch of half-baked ideas"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	readingTime = true
  readingTimeText = "Estimated reading time:"
	mode = "auto" # "dark", "auto", "light"
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:scottfrechette@gmail.com" 

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/scotfrechette"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/scott-frechette/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
